server:
  #应用启动端口号
  port: 8082
spring:
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  #数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/message_system?useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring-boot-jpa配置（并未使用）
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  #用于捕获404异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#页面映射（已不使用）
mvc:
  view:
    prefix: /templates/
    suffix: .html
#mybatis相关配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.message.entity
# jwt 配置
custom:
  jwt:
    # header:凭证(校验的变量名)
    header: Authorization
    # 有效期1天(单位:s)
    #expire: 5184000
    # token有效期s
    expire: 86400
    # secret: 秘钥(普通字符串) 不能太短，太短可能会导致报错
    secret: 99c2918fe19d30bce25abfac8a3733ec
    # 签发者
    issuer: kbdog
